apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-the-strokes
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sebastianlopezanido/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
