apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-the-strokes
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: lopeza74/the-strokes-api:02
        ports:
        - containerPort: 3000
