apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-encoder
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: selopezavalian/api-encoder64:prod-0.1.19
        ports:
        - containerPort: 8080
